name: ib_manifest_env
channels:
  - conda-forge
  - default
dependencies:
  - click
  - jinja2
  - pip
  - pre-commit
  - pytest
  - pytest-cov
  - python=3.11
  - requests
  - ruamel.yaml
  - urllib3
  - pip:
    - git+https://github.com/309thEDDGE/conda-vendor.git
    - .
